stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.12"
  POETRY_NO_INTERACTION: 1
  POETRY_VIRTUALENVS_CREATE: 'false'
  POETRY_CACHE_DIR: '/var/cache/pypoetry'
  POETRY_HOME: '/usr/local'
  GITLAB_TOKEN: 'glpat-N6a3yxvc6rKzT17bVZX4'

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry config http-basic.gitlab-payment __token__ $GITLAB_TOKEN
    - poetry install --with test
    - flake8

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry config http-basic.gitlab-payment __token__ $GITLAB_TOKEN
    - poetry install --with test
    - cd src/market
    - pytest --cov
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'