stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.12"

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  before_script:
    # Configure git to use the token for your GitLab instance
    - 'git config --global url."https://oauth2:$GITLAB_TOKEN@gitlab.inesctec.pt/".insteadOf "https://gitlab.inesctec.pt/"'
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry install
    - pip install flake8
    - flake8

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry install
    - cd src/market
    - pytest --cov
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'