version: "3.7"
services:

  app:
    build:
      context: .
      args:
        - GITLAB_TOKEN
    container_name: valorem-market
    volumes:
      - storage:/app/files
    env_file:
      - .env

volumes:
  storage:
